---
- name: example of fetch
  hosts: 192.168.1.21
  tasks:
   - name: copy file
     fetch:
       src: /home/lulu.html
       dest: /tmp/
       flat: yes
   - delegate_to: all
     copy:
       content: "{{ lookup('file','/tmp/lulu.html') }}"
       dest: /tmp/lulu.html

