---
- name: handler
  hosts: all
  tasks:
    - name: check service
      yum:
       name: httpd
       state: present
    - name: copy code
      copy:
        src: ./hand.html
        dest: /var/www/html/index.html
      notify: restart
  handlers:
    - name: restart
      service:
        name: httpd
        state: restarted 

